DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS CREDITS;
DROP TABLE IF EXISTS CROFFERS;

CREATE TABLE CLIENTS (
	client_id SMALLINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	last_name VARCHAR(255),
	first_name VARCHAR(255),
	middle_name VARCHAR(255),
	phone_number VARCHAR(15),
	email VARCHAR(50),
	passport_number VARCHAR(12));
	
CREATE TABLE CREDITS (
	credit_id SMALLINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	loan_limit VARCHAR(15),
	interest_rate VARCHAR(30));
	
CREATE TABLE CROFFERS (
	offer_id SMALLINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	client_id SMALLINT,
	credit_id SMALLINT,
	credit_sum INT,
	payment_date VARCHAR(15),
	payment_sum INT,
	loan_body INT,
	loan_interest INT,
	FOREIGN KEY (client_id) REFERENCES CLIENTS (client_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (credit_id) REFERENCES CREDITS (credit_id) ON DELETE CASCADE ON UPDATE CASCADE
	);
	
	
INSERT INTO CLIENTS (last_name, first_name, middle_name, phone_number, email, 
																passport_number)
VALUES ('Barkins', 'Jack', 'Maining', '+4125938562438', 'j.barkins@mail.ru', '3215');

INSERT INTO CLIENTS (last_name, first_name, middle_name, phone_number, email, 
																passport_number)
VALUES ('Callinz', 'John', 'Campus', '+4124678283328', 'j.callinz@mail.ru', '3627');

INSERT INTO CLIENTS (last_name, first_name, middle_name, phone_number, email, 
																passport_number)
VALUES ('Fried', 'Nick', 'Scrolling', '+4123856395630', 'n.fried@gmail.com', '9025');

INSERT INTO CLIENTS (last_name, first_name, middle_name, phone_number, email, 
																passport_number)
VALUES ('Hapler', 'Joshua', 'Vanning', '+4123647382749', 'j.hapler@rambler.ru', '3874');

INSERT INTO CLIENTS (last_name, first_name, middle_name, phone_number, email, 
																passport_number)
VALUES ('Grootis', 'Silvestr', 'Sqash', '+4124839635949', 's.grootis@protonmail.com', '3542');


INSERT INTO CREDITS (loan_limit, interest_rate)
VALUES ('20000', '17');

INSERT INTO CREDITS (loan_limit, interest_rate)
VALUES ('50000', '11');

INSERT INTO CREDITS (loan_limit, interest_rate)
VALUES ('15000', '13');

INSERT INTO CREDITS (loan_limit, interest_rate)
VALUES ('30000', '15');

INSERT INTO CREDITS (loan_limit, interest_rate)
VALUES ('25000', '14');


INSERT INTO CROFFERS (client_id, credit_id, credit_sum, payment_date, payment_sum, loan_body,
					  loan_interest)
VALUES (1, 3, 200000, '23.12.2021', 20000, 13000, 7000);

INSERT INTO CROFFERS (client_id, credit_id, credit_sum, payment_date, payment_sum, loan_body,
					  loan_interest)
VALUES (2, 1, 300000, '13.11.2021', 30000, 23000, 7000);

INSERT INTO CROFFERS (client_id, credit_id, credit_sum, payment_date, payment_sum, loan_body,
					  loan_interest)
VALUES (3, 2, 150000, '21.10.2021', 15000, 11000, 4000);

INSERT INTO CROFFERS (client_id, credit_id, credit_sum, payment_date, payment_sum, loan_body,
					  loan_interest)
VALUES (4, 4, 250000, '8.09.2021', 25000, 18000, 7000);

INSERT INTO CROFFERS (client_id, credit_id, credit_sum, payment_date, payment_sum, loan_body,
					  loan_interest)
VALUES (5, 5, 400000, '14.08.2021', 40000, 30000, 10000);